# Generated by Django 4.2.23 on 2025-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_on',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(default=False),
        ),
    ]
